/**
 * Phase 8: Saturn-IB vertical slice models must code-generate cleanly
 * with the new block library (no new primitives — composition only).
 */

import * as fs from 'fs'
import * as path from 'path'
import { CodeGenerator } from '@/lib/codegen/CodeGenerator'
import {
  allSaturnSlices,
  sliceToModelData,
  buildGravityBallistics,
  buildSixDofVacuumKinematics,
  buildEngineThrustTimer,
  buildAtmosphereDynamicPressure,
  buildStageEnableFreeze,
  buildRateModulator,
  buildChiTimeTilt,
  buildIgmModeShell,
  buildFccFilter,
  buildOpenLoopAscent1D
} from '../examples/saturn-ib/sliceModels'

const OUT_DIR = path.join(__dirname, '../docs/sample-models/saturn')

describe('Saturn-IB Phase 8 vertical slices', () => {
  beforeAll(() => {
    fs.mkdirSync(OUT_DIR, { recursive: true })
  })

  const slices = allSaturnSlices()

  test.each(slices.map(s => [s.name, s] as const))(
    'codegen: %s',
    (_name, slice) => {
      const gen = new CodeGenerator({
        modelName: slice.name.replace(/[^a-zA-Z0-9_]/g, '_'),
        integrationAlgorithm: slice.globalSettings.integrationAlgorithm || 'rk4'
      })
      const result = gen.generate(slice.sheets as any, slice.parameters || [])

      expect(result.header).toContain('_t')
      expect(result.source).toContain('_step')
      expect(result.source).toContain('_evaluate_algebraic')
      // No hard ERROR comments from failed block modules
      expect(result.source).not.toMatch(/Error generating code for/)
    }
  )

  test('exports JSON fixtures under docs/sample-models/saturn/', () => {
    for (const slice of slices) {
      const data = sliceToModelData(slice)
      const filePath = path.join(OUT_DIR, `${slice.name}.json`)
      fs.writeFileSync(
        filePath,
        JSON.stringify(
          {
            name: slice.name,
            data
          },
          null,
          2
        )
      )
      expect(fs.existsSync(filePath)).toBe(true)
    }

    const readme = path.join(OUT_DIR, 'README.md')
    fs.writeFileSync(
      readme,
      `# Saturn-IB sample models (Phase 8)

Generated by \`__tests__/saturn-ib-slices.test.ts\` from \`examples/saturn-ib/sliceModels.ts\`.

| Model | Description |
|-------|-------------|
${slices.map(s => `| \`${s.name}.json\` | ${s.description} |`).join('\n')}

## Blocks exercised

| Slice | New / key blocks |
|-------|------------------|
| 8.1 gravity | integrator x(0), divide, multiply, uminus |
| 8.3 engine timer | edge_detect, integrator reset, lookup_1d |
| 8.4 atmosphere q̄ | atmosphere (4 outs), multiply |
| 8.6 FCC | transfer_function, limit |
| 8.7 rate modulator | relay, unit_delay |
| 8.8 chi time-tilt | lookup_1d, rate_limiter, clock |
| 8.9 IGM mode | data_store_write/read, evaluate |

AS-205 constants from \`saturn-1B/AS205_presettings.m\` are included on relevant models as model parameters.
`
    )
    expect(fs.existsSync(readme)).toBe(true)
  })

  test('8.1 gravity model wires integrator x(0) ports', () => {
    const m = buildGravityBallistics()
    const r = m.sheets[0].blocks.find(b => b.name === 'r')
    expect(r?.parameters?.showInitPort).toBe(true)
    const initWires = m.sheets[0].connections.filter(
      c => c.targetBlockId === r!.id && c.targetPortIndex === 1
    )
    expect(initWires.length).toBe(1)
  })

  test('8.3 engine timer uses edge_detect and reset port -2', () => {
    const m = buildEngineThrustTimer()
    const edge = m.sheets[0].blocks.find(b => b.type === 'edge_detect')
    expect(edge).toBeDefined()
    const resetWire = m.sheets[0].connections.find(c => c.targetPortIndex === -2)
    expect(resetWire).toBeDefined()
    expect(m.sheets[0].blocks.some(b => b.type === 'lookup_1d')).toBe(true)
  })

  test('8.4 atmosphere density is port 2', () => {
    const m = buildAtmosphereDynamicPressure()
    const densWires = m.sheets[0].connections.filter(
      c =>
        c.sourcePortIndex === 2 &&
        m.sheets[0].blocks.find(b => b.id === c.sourceBlockId)?.type === 'atmosphere'
    )
    expect(densWires.length).toBeGreaterThanOrEqual(1)
  })

  test('8.7 rate modulator has relay and unit_delay', () => {
    const m = buildRateModulator()
    expect(m.sheets[0].blocks.some(b => b.type === 'relay')).toBe(true)
    expect(m.sheets[0].blocks.some(b => b.type === 'unit_delay')).toBe(true)
  })

  test('8.8 chi uses rate_limiter', () => {
    const m = buildChiTimeTilt()
    expect(m.sheets[0].blocks.some(b => b.type === 'rate_limiter')).toBe(true)
  })

  test('8.9 IGM uses data stores for nIGMMode', () => {
    const m = buildIgmModeShell()
    const w = m.sheets[0].blocks.find(b => b.type === 'data_store_write')
    const r = m.sheets[0].blocks.find(b => b.type === 'data_store_read')
    expect(w?.parameters?.storeName).toBe('nIGMMode')
    expect(r?.parameters?.storeName).toBe('nIGMMode')
  })

  test('8.6 FCC has transfer_function', () => {
    const m = buildFccFilter()
    expect(m.sheets[0].blocks.some(b => b.type === 'transfer_function')).toBe(true)
  })

  test('8.2 6DoF uses body2quaternion_rates and quat IC', () => {
    const m = buildSixDofVacuumKinematics()
    expect(m.sheets[0].blocks.some(b => b.type === 'body2quaternion_rates')).toBe(true)
    const q0 = m.sheets[0].blocks.find(b => b.name === 'q0')
    expect(q0?.parameters?.dataType).toBe('double[4][1]')
    const qInt = m.sheets[0].blocks.find(b => b.name === 'q')
    expect(qInt?.parameters?.showInitPort).toBe(true)
  })

  test('8.5 stage subsystem has enable wired to port -1', () => {
    const m = buildStageEnableFreeze()
    const stage = m.sheets[0].blocks.find(b => b.type === 'subsystem')
    expect(stage?.parameters?.showEnableInput).toBe(true)
    const enWire = m.sheets[0].connections.find(
      c => c.targetBlockId === stage!.id && c.targetPortIndex === -1
    )
    expect(enWire).toBeDefined()
  })

  test('8.10 open-loop ascent combines edge, thrust, gravity, atmosphere', () => {
    const m = buildOpenLoopAscent1D()
    const types = new Set(m.sheets[0].blocks.map(b => b.type))
    expect(types.has('edge_detect')).toBe(true)
    expect(types.has('lookup_1d')).toBe(true)
    expect(types.has('atmosphere')).toBe(true)
    expect(types.has('integrator')).toBe(true)
    expect(types.has('divide')).toBe(true)
  })
})
