# .github/workflows/code-generation-tests.yml
name: Code Generation Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'
        
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        
    - name: Install PlatformIO
      run: |
        pip install platformio
        pio --version
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run code generation tests
      run: npm run test:codegen