/**
 * WASM Code Generator
 *
 * Extends the base CodeGenerator to add WebAssembly-specific features:
 * - EMSCRIPTEN_KEEPALIVE macros for exported functions
 * - Simplified interface functions for JS interop
 * - Input/output index mapping
 * - Memory management helpers
 */

import { CodeGenerator, CodeGenerationOptions, CodeGenerationResult } from '@/lib/codegen/CodeGenerator'
import { Sheet } from '@/lib/simulationTypes'
import { CCodeBuilder } from '@/lib/codegen/CCodeBuilder'
import { ModelFlattener } from '@/lib/codegen/ModelFlattener'
import { TypePropagator } from '@/lib/codegen/TypePropagator'
import { getSignalMemberName } from '@/lib/codegen/signalMemberName'

export interface WasmCodeGenerationOptions extends CodeGenerationOptions {
  /** Whether to include Emscripten-specific exports (default: true) */
  includeEmscriptenExports?: boolean

  /** Whether to include debug/logging functions (default: false) */
  includeDebugFunctions?: boolean
}

export interface WasmCodeGenerationResult extends CodeGenerationResult {
  /** Model name (for reference) */
  modelName: string

  /** Generated WASM wrapper file content */
  wasmWrapper: string

  /** Input port index mapping */
  inputMap: Map<string, number>

  /** Output port index mapping */
  outputMap: Map<string, number>
}

/**
 * Code generator that produces WASM-compatible C code
 */
export class WasmCodeGenerator extends CodeGenerator {
  private wasmOptions: Required<WasmCodeGenerationOptions>

  constructor(options: WasmCodeGenerationOptions = {}) {
    super(options)
    this.wasmOptions = {
      ...this.options,
      includeEmscriptenExports: options.includeEmscriptenExports ?? true,
      includeDebugFunctions: options.includeDebugFunctions ?? false
    }
  }

  /**
   * Generate C code with WASM exports
   */
  generateWasm(sheets: Sheet[], parameters: any[] = []): WasmCodeGenerationResult {
    // Generate base code using parent class
    const baseResult = this.generate(sheets, parameters)

    // Flatten the model to run type propagation (same as base code generation does)
    const flattener = new ModelFlattener({
      preserveOriginalNames: true,
      generateEnableTracking: true,
      namePrefix: '',
      nameSeparator: '_'
    })

    const flatteningResult = flattener.flattenModel(sheets, this.options.modelName, parameters)
    const typePropagator = new TypePropagator(flatteningResult.model)
    const typeMap = typePropagator.propagate()

    console.log(`[WasmCodeGenerator] typeMap entries:`, Array.from(typeMap.entries()))
    console.log(`[WasmCodeGenerator] flattenedModel.blocks:`, flatteningResult.model.blocks.map((b: any) => ({ originalId: b.originalId, name: b.block.name, type: b.block.type })))

    // Extract input/output mappings with type information
    const { inputMap, outputMap, outputSourceMap, collectorTypeMap, outputTypeMap } = this.extractPortMappings(sheets, typeMap, flatteningResult.model)

    // Check if cleanup function was actually generated by examining the header
    // This is the authoritative source - if the header doesn't declare it, it doesn't exist
    const sanitizedName = CCodeBuilder.sanitizeIdentifier(this.options.modelName)
    const hasCleanupFunction = baseResult.header.includes(`${sanitizedName}_cleanup`)

    console.log(`[WasmCodeGenerator] Model: ${sanitizedName}, hasCleanupFunction: ${hasCleanupFunction}`)
    if (hasCleanupFunction) {
      console.log('[WasmCodeGenerator] Cleanup function found in header')
    } else {
      console.log('[WasmCodeGenerator] No cleanup function in header - will generate empty wrapper')
    }

    // Generate WASM wrapper
    const wasmWrapper = this.generateWasmWrapper(
      this.options.modelName,
      inputMap,
      outputMap,
      outputSourceMap,
      collectorTypeMap,
      outputTypeMap,
      hasCleanupFunction
    )

    return {
      ...baseResult,
      modelName: this.options.modelName,
      wasmWrapper,
      inputMap,
      outputMap
    }
  }

  /**
   * Extract input and output port mappings for index-based access
   *
   * Includes:
   * - input_port blocks as inputs
   * - output_port blocks as outputs
   * - signal_logger blocks as outputs (for scope data retrieval)
   * - signal_display blocks as outputs (for visualization data retrieval)
   */
  private extractPortMappings(
    sheets: Sheet[],
    typeMap: Map<string, string>,
    flattenedModel: any
  ): {
    inputMap: Map<string, number>
    outputMap: Map<string, number>
    outputSourceMap: Map<string, {
      blockName: string
      blockType: string
      isSubsystem: boolean
      isFlattened: boolean
      portIndex: number
      outputPortName?: string
      flattenedSignalPath?: string
      signalMemberName?: string
      sourceBlock?: any
    }>
    collectorTypeMap: Map<string, string> // Maps collector name to input signal type
    outputTypeMap: Map<string, string> // Maps output port name to signal type
  } {
    const inputMap = new Map<string, number>()
    const outputMap = new Map<string, number>()
    const outputSourceMap = new Map<string, {
      blockName: string
      blockType: string
      isSubsystem: boolean
      isFlattened: boolean
      portIndex: number
      outputPortName?: string
      flattenedSignalPath?: string
      signalMemberName?: string
      sourceBlock?: any
    }>()
    const collectorTypeMap = new Map<string, string>()
    const outputTypeMap = new Map<string, string>()

    let inputIndex = 0
    let outputIndex = 0

    // Helper function to get type from typeMap
    const getBlockType = (blockId: string, fallbackType: string = 'double'): string => {
      // Find the flattened block by original ID
      const flattenedBlock = flattenedModel.blocks.find((fb: any) => fb.originalId === blockId)
      if (flattenedBlock) {
        const mappedType = typeMap.get(flattenedBlock.originalId)
        console.log(`[getBlockType] blockId=${blockId}, flattenedBlock.originalId=${flattenedBlock.originalId}, mappedType=${mappedType}`)
        if (mappedType) {
          return mappedType
        }
      } else {
        console.log(`[getBlockType] blockId=${blockId}, flattenedBlock not found`)
      }
      return fallbackType
    }

    /**
     * Trace the internal block that feeds a subsystem output port.
     * Returns { path, type } for flattened signal access and scalar filtering.
     */
    const resolveSubsystemOutput = (
      subsystemBlock: any,
      outputPortIndex: number
    ): { path?: string; type: string; internalSource?: any } => {
      const codeGenStrategy = subsystemBlock.parameters?.codeGenStrategy || 'flatten'
      if (codeGenStrategy === 'segregated' || codeGenStrategy === 'segregated_atomic') {
        return { type: 'double' }
      }

      const subsystemSheets = subsystemBlock.parameters?.sheets as Sheet[] | undefined
      if (!subsystemSheets) return { type: 'double' }

      const outputPorts = subsystemBlock.parameters?.outputPorts as string[] | undefined
      if (!outputPorts) return { type: 'double' }

      const targetPortName = outputPorts[outputPortIndex]
      if (!targetPortName) return { type: 'double' }

      for (const subSheet of subsystemSheets) {
        const outputPortBlock = subSheet.blocks.find(
          (b: any) => b.type === 'output_port' && b.parameters?.portName === targetPortName
        )
        if (!outputPortBlock) continue

        const feedingConn = subSheet.connections.find(
          (c: any) => c.targetBlockId === outputPortBlock.id
        )
        if (!feedingConn) continue

        const sourceBlock = subSheet.blocks.find((b: any) => b.id === feedingConn.sourceBlockId)
        if (!sourceBlock) continue

        if (sourceBlock.type === 'input_port') {
          // Passthrough of subsystem input — type from input_port dataType
          return {
            type: sourceBlock.parameters?.dataType || 'double',
            internalSource: sourceBlock,
          }
        }

        const subsystemName = CCodeBuilder.sanitizeIdentifier(subsystemBlock.name)
        // Multi-output internal blocks need port suffix; single-out use Subsystem_BlockName
        let path: string
        if (
          sourceBlock.type === 'atmosphere' ||
          sourceBlock.type === 'orientation_conversion' ||
          sourceBlock.type === 'demux'
        ) {
          path = getSignalMemberName(
            `${subsystemName}_${sourceBlock.name}`,
            sourceBlock.type,
            feedingConn.sourcePortIndex,
            { ...sourceBlock, name: `${subsystemName}_${sourceBlock.name}` }
          )
        } else {
          path = `${subsystemName}_${CCodeBuilder.sanitizeIdentifier(sourceBlock.name)}`
        }

        // Type from type propagator (key is original nested block id)
        let signalType =
          typeMap.get(sourceBlock.id) ||
          getBlockType(sourceBlock.id, sourceBlock.parameters?.dataType || 'double')

        // Fallback: scan flattened model for matching block under this subsystem
        if (!signalType || signalType === 'double') {
          const fb = flattenedModel.blocks.find(
            (b: any) =>
              b.block?.name === sourceBlock.name ||
              b.flattenedName === `${subsystemBlock.name}_${sourceBlock.name}` ||
              b.flattenedName?.endsWith(`_${sourceBlock.name}`)
          )
          if (fb) {
            const t = typeMap.get(fb.originalId)
            if (t) signalType = t
          }
        }

        if (sourceBlock.parameters?.dataType && sourceBlock.parameters.dataType.includes('[')) {
          signalType = sourceBlock.parameters.dataType
        } else if (sourceBlock.parameters?.outputType && sourceBlock.parameters.outputType.includes('[')) {
          signalType = sourceBlock.parameters.outputType
        } else if (!signalType || signalType === 'double') {
          // EOM-style vector/quaternion names when type map is incomplete
          const n = sourceBlock.name
          if (n === 'r_i' || n === 'v_b' || n === 'omega_b' || n === 'F_b' || n === 'M_b') {
            signalType = 'double[3]'
          } else if (n === 'q' || n === 'q_hat' || n === 'q_raw') {
            signalType = 'double[4][1]'
          }
        }

        return {
          path,
          type: signalType || 'double',
          internalSource: sourceBlock,
        }
      }

      return { type: 'double' }
    }

    // Helper function to find the flattened signal path for a subsystem output port
    // For flattened subsystems, we need to trace inside to find the block that feeds the output port
    const getFlattenedSignalPath = (subsystemBlock: any, outputPortIndex: number): string | undefined => {
      return resolveSubsystemOutput(subsystemBlock, outputPortIndex).path
    }

    const getSourceSignalType = (
      sourceBlock: any,
      sourcePortIndex: number
    ): string => {
      if (sourceBlock.type === 'subsystem') {
        return resolveSubsystemOutput(sourceBlock, sourcePortIndex).type
      }
      // Multi-output blocks: all scalar ports unless known otherwise
      if (sourceBlock.type === 'atmosphere') {
        return 'double'
      }
      return getBlockType(
        sourceBlock.id,
        sourceBlock.parameters?.dataType || sourceBlock.parameters?.outputType || 'double'
      )
    }

    // Process all sheets to find input/output ports and signal loggers
    for (const sheet of sheets) {
      for (const block of sheet.blocks) {
        if (block.type === 'input_port') {
          const portName = block.parameters?.portName || block.name
          inputMap.set(portName, inputIndex++)
        } else if (block.type === 'output_port') {
          const portName = block.parameters?.portName || block.name
          outputMap.set(portName, outputIndex++)

          // Find the connection that feeds this output port
          const feedingConnection = sheet.connections.find(conn => conn.targetBlockId === block.id)
          if (feedingConnection) {
            const sourceBlock = sheet.blocks.find(b => b.id === feedingConnection.sourceBlockId)
            if (sourceBlock) {
              const isSubsystem = sourceBlock.type === 'subsystem'
              // For subsystems, find the output port name from the subsystem's outputPorts parameter
              let outputPortName: string | undefined
              let isFlattened = false
              let flattenedSignalPath: string | undefined
              if (isSubsystem) {
                const outputPorts = sourceBlock.parameters?.outputPorts as string[] | undefined
                if (outputPorts) {
                  outputPortName = outputPorts[feedingConnection.sourcePortIndex] || outputPorts[0]
                }
                // Check if subsystem is flattened and get the signal path
                const codeGenStrategy = sourceBlock.parameters?.codeGenStrategy || 'flatten'
                isFlattened = codeGenStrategy === 'flatten'
                if (isFlattened) {
                  flattenedSignalPath = getFlattenedSignalPath(sourceBlock, feedingConnection.sourcePortIndex)
                }
              }
              outputSourceMap.set(portName, {
                blockName: sourceBlock.name,
                blockType: sourceBlock.type,
                isSubsystem,
                isFlattened,
                portIndex: feedingConnection.sourcePortIndex,
                outputPortName,
                flattenedSignalPath,
                signalMemberName: isSubsystem
                  ? undefined
                  : getSignalMemberName(
                      sourceBlock.name,
                      sourceBlock.type,
                      feedingConnection.sourcePortIndex,
                      sourceBlock
                    ),
                sourceBlock,
              })
              // Resolve type including nested subsystem outputs (vectors must not go to wasm_get_output)
              const sourceType = getSourceSignalType(
                sourceBlock,
                feedingConnection.sourcePortIndex
              )
              outputTypeMap.set(portName, sourceType)
            }
          }
        } else if (block.type === 'signal_logger') {
          // Treat signal loggers as outputs for scope data access
          // Use sanitized block name to avoid issues with spaces
          const loggerName = `logger_${CCodeBuilder.sanitizeIdentifier(block.name)}`
          outputMap.set(loggerName, outputIndex++)

          // Find the connection that feeds this signal logger
          const feedingConnection = sheet.connections.find(conn => conn.targetBlockId === block.id)
          if (feedingConnection) {
            const sourceBlock = sheet.blocks.find(b => b.id === feedingConnection.sourceBlockId)
            if (sourceBlock) {
              const isSubsystem = sourceBlock.type === 'subsystem'
              let outputPortName: string | undefined
              let isFlattened = false
              let flattenedSignalPath: string | undefined
              if (isSubsystem) {
                const outputPorts = sourceBlock.parameters?.outputPorts as string[] | undefined
                if (outputPorts) {
                  outputPortName = outputPorts[feedingConnection.sourcePortIndex] || outputPorts[0]
                }
                const codeGenStrategy = sourceBlock.parameters?.codeGenStrategy || 'flatten'
                isFlattened = codeGenStrategy === 'flatten'
                if (isFlattened) {
                  flattenedSignalPath = getFlattenedSignalPath(sourceBlock, feedingConnection.sourcePortIndex)
                }
              }
              outputSourceMap.set(loggerName, {
                blockName: sourceBlock.name,
                blockType: sourceBlock.type,
                isSubsystem,
                isFlattened,
                portIndex: feedingConnection.sourcePortIndex,
                outputPortName,
                flattenedSignalPath,
                signalMemberName: isSubsystem
                  ? undefined
                  : getSignalMemberName(
                      sourceBlock.name,
                      sourceBlock.type,
                      feedingConnection.sourcePortIndex,
                      sourceBlock
                    ),
                sourceBlock,
              })
              const sourceType = getSourceSignalType(
                sourceBlock,
                feedingConnection.sourcePortIndex
              )
              collectorTypeMap.set(loggerName, sourceType)
            }
          }
        } else if (block.type === 'signal_display') {
          // Treat signal displays as outputs for visualization data access
          // Use sanitized block name to avoid issues with spaces
          const displayName = `display_${CCodeBuilder.sanitizeIdentifier(block.name)}`
          outputMap.set(displayName, outputIndex++)

          // Find the connection that feeds this signal display
          const feedingConnection = sheet.connections.find(conn => conn.targetBlockId === block.id)
          if (feedingConnection) {
            const sourceBlock = sheet.blocks.find(b => b.id === feedingConnection.sourceBlockId)
            if (sourceBlock) {
              const isSubsystem = sourceBlock.type === 'subsystem'
              let outputPortName: string | undefined
              let isFlattened = false
              let flattenedSignalPath: string | undefined
              if (isSubsystem) {
                const outputPorts = sourceBlock.parameters?.outputPorts as string[] | undefined
                if (outputPorts) {
                  outputPortName = outputPorts[feedingConnection.sourcePortIndex] || outputPorts[0]
                }
                const codeGenStrategy = sourceBlock.parameters?.codeGenStrategy || 'flatten'
                isFlattened = codeGenStrategy === 'flatten'
                if (isFlattened) {
                  flattenedSignalPath = getFlattenedSignalPath(sourceBlock, feedingConnection.sourcePortIndex)
                }
              }
              outputSourceMap.set(displayName, {
                blockName: sourceBlock.name,
                blockType: sourceBlock.type,
                isSubsystem,
                isFlattened,
                portIndex: feedingConnection.sourcePortIndex,
                outputPortName,
                flattenedSignalPath,
                signalMemberName: isSubsystem
                  ? undefined
                  : getSignalMemberName(
                      sourceBlock.name,
                      sourceBlock.type,
                      feedingConnection.sourcePortIndex,
                      sourceBlock
                    ),
                sourceBlock,
              })
              const sourceType = getSourceSignalType(
                sourceBlock,
                feedingConnection.sourcePortIndex
              )
              collectorTypeMap.set(displayName, sourceType)
            }
          }
        }
      }
    }

    return { inputMap, outputMap, outputSourceMap, collectorTypeMap, outputTypeMap }
  }

  /**
   * Generate WASM wrapper file with Emscripten exports
   */
  private generateWasmWrapper(
    modelName: string,
    inputMap: Map<string, number>,
    outputMap: Map<string, number>,
    outputSourceMap: Map<string, {
      blockName: string
      blockType: string
      isSubsystem: boolean
      isFlattened: boolean
      portIndex: number
      outputPortName?: string
      flattenedSignalPath?: string
      signalMemberName?: string
      sourceBlock?: any
    }>,
    collectorTypeMap: Map<string, string>,
    outputTypeMap: Map<string, string>,
    hasCleanupFunction: boolean
  ): string {
    const sanitizedName = CCodeBuilder.sanitizeIdentifier(modelName)
    let wrapper = ''

    // Header comments
    const exportNote = this.wasmOptions.includeEmscriptenExports
      ? '\n * Functions are exported using EMSCRIPTEN_KEEPALIVE for direct calling from JS.'
      : ''
    wrapper += `/*
 * WASM Wrapper for ${modelName}
 *
 * This file provides a simple interface for WebAssembly/JavaScript interop.${exportNote}
 */

`

    // Includes
    wrapper += `#include "${sanitizedName}.h"\n\n`

    if (this.wasmOptions.includeEmscriptenExports) {
      wrapper += `#ifdef __EMSCRIPTEN__
#include <emscripten.h>
#else
#define EMSCRIPTEN_KEEPALIVE
#endif

`
    }

    // Global model instance
    wrapper += `// Global model instance
static ${sanitizedName}_t ${sanitizedName}_instance = {0};

`

    // Input/output name arrays (for debugging)
    if (this.wasmOptions.includeDebugFunctions) {
      wrapper += this.generatePortNameArrays(inputMap, outputMap)
    }

    // Data collector name array (for sample retrieval)
    wrapper += this.generateDataCollectorNameArray(outputMap)

    // Output port name array (for output port enumeration)
    wrapper += this.generateOutputPortNameArray(outputMap)

    // Initialize function
    wrapper += this.generateWasmInitFunction(sanitizedName)

    // Set input function
    wrapper += this.generateWasmSetInputFunction(sanitizedName, inputMap)

    // Get output function
    wrapper += this.generateWasmGetOutputFunction(sanitizedName, outputMap, outputSourceMap, outputTypeMap)

    // Step function
    wrapper += this.generateWasmStepFunction(sanitizedName)

    // Get time function
    wrapper += this.generateWasmGetTimeFunction(sanitizedName)

    // Data collection functions (for logger/display sample retrieval)
    wrapper += this.generateDataCollectionFunctions(sanitizedName, outputMap, collectorTypeMap)

    // Output port info functions (for enumerating and displaying output port values)
    wrapper += this.generateOutputPortInfoFunctions(sanitizedName, outputMap)

    // Cleanup function (always generate, but conditionally call C cleanup based on what was actually generated)
    wrapper += this.generateWasmCleanupFunction(sanitizedName, hasCleanupFunction)

    // Debug functions (optional)
    if (this.wasmOptions.includeDebugFunctions) {
      wrapper += this.generateWasmDebugFunctions(sanitizedName, inputMap, outputMap)
    }

    return wrapper
  }

  /**
   * Generate port name arrays for debugging
   */
  private generatePortNameArrays(
    inputMap: Map<string, number>,
    outputMap: Map<string, number>
  ): string {
    let code = '// Port name mappings for debugging\n'

    // Input names
    code += `static const char* input_names[] = {\n`
    const sortedInputs = Array.from(inputMap.entries())
      .sort((a, b) => a[1] - b[1])
    sortedInputs.forEach(([name], idx) => {
      code += `    "${name}"${idx < sortedInputs.length - 1 ? ',' : ''}\n`
    })
    code += `};\n\n`

    // Output names
    code += `static const char* output_names[] = {\n`
    const sortedOutputs = Array.from(outputMap.entries())
      .sort((a, b) => a[1] - b[1])
    sortedOutputs.forEach(([name], idx) => {
      code += `    "${name}"${idx < sortedOutputs.length - 1 ? ',' : ''}\n`
    })
    code += `};\n\n`

    return code
  }

  /**
   * Generate wasm_init function
   */
  private generateWasmInitFunction(modelName: string): string {
    const keepalive = this.wasmOptions.includeEmscriptenExports
      ? 'EMSCRIPTEN_KEEPALIVE\n'
      : ''

    return `// Initialize the model with a given timestep
${keepalive}void wasm_init(double dt) {
    ${modelName}_init(&${modelName}_instance, dt);
}

`
  }

  /**
   * Generate wasm_set_input function
   */
  private generateWasmSetInputFunction(
    modelName: string,
    inputMap: Map<string, number>
  ): string {
    const keepalive = this.wasmOptions.includeEmscriptenExports
      ? 'EMSCRIPTEN_KEEPALIVE\n'
      : ''

    let code = `// Set an input value by index
${keepalive}void wasm_set_input(int index, double value) {
    switch(index) {\n`

    // Generate switch cases for each input
    const sortedInputs = Array.from(inputMap.entries())
      .sort((a, b) => a[1] - b[1])

    sortedInputs.forEach(([portName, index]) => {
      const sanitizedPort = CCodeBuilder.sanitizeIdentifier(portName)
      code += `        case ${index}: ${modelName}_instance.inputs.${sanitizedPort} = value; break;\n`
    })

    code += `        default: break; // Invalid index\n`
    code += `    }\n`
    code += `}\n\n`

    return code
  }

  /**
   * Generate wasm_get_output function
   */
  private generateWasmGetOutputFunction(
    modelName: string,
    outputMap: Map<string, number>,
    outputSourceMap: Map<string, {
      blockName: string
      blockType: string
      isSubsystem: boolean
      isFlattened: boolean
      portIndex: number
      outputPortName?: string
      flattenedSignalPath?: string
      signalMemberName?: string
      sourceBlock?: any
    }>,
    outputTypeMap: Map<string, string>
  ): string {
    const keepalive = this.wasmOptions.includeEmscriptenExports
      ? 'EMSCRIPTEN_KEEPALIVE\n'
      : ''

    let code = `// Get an output value by index
// Note: Only supports scalar outputs. For vector/matrix data, use Signal Display blocks.
${keepalive}double wasm_get_output(int index) {
    switch(index) {\n`

    // Generate switch cases for each output
    console.log(`[WasmCodeGenerator] outputMap entries:`, Array.from(outputMap.entries()))
    console.log(`[WasmCodeGenerator] outputTypeMap entries:`, Array.from(outputTypeMap.entries()))

    const sortedOutputs = Array.from(outputMap.entries())
      .sort((a, b) => a[1] - b[1])
      // Filter out logger and display blocks - they're not real output ports
      .filter(([name]) => !name.startsWith('logger_') && !name.startsWith('display_'))
      // Filter out vector/matrix outputs - only support scalars
      .filter(([name]) => {
        const outputType = outputTypeMap.get(name) || 'double'
        console.log(`[WasmCodeGenerator] Checking output ${name}: type=${outputType}, isScalar=${!outputType.includes('[')}`)
        // Check if it's a scalar (no array brackets)
        return !outputType.includes('[')
      })

    console.log(`[WasmCodeGenerator] Filtered outputs for wasm_get_output:`, sortedOutputs)

    if (sortedOutputs.length > 0) {
      sortedOutputs.forEach(([portName, index]) => {
        // Output ports are fed by signals, not stored directly in outputs struct
        // Use the source info if available
        const sourceInfo = outputSourceMap.get(portName)
        if (sourceInfo) {
          if (sourceInfo.isSubsystem) {
            if (sourceInfo.isFlattened && sourceInfo.flattenedSignalPath) {
              // Flattened subsystem: use the flattened signal path in signals struct
              code += `        case ${index}: return ${modelName}_instance.signals.${sourceInfo.flattenedSignalPath};\n`
            } else if (!sourceInfo.isFlattened) {
              // Segregated subsystem: outputs are accessed via model->SubsystemName.outputs.PortName
              const sanitizedSubsystem = CCodeBuilder.sanitizeIdentifier(sourceInfo.blockName)
              const sanitizedPort = CCodeBuilder.sanitizeIdentifier(sourceInfo.outputPortName || 'Output1')
              code += `        case ${index}: return ${modelName}_instance.${sanitizedSubsystem}.outputs.${sanitizedPort};\n`
            } else {
              // Flattened but couldn't trace signal path - skip with comment
              code += `        // case ${index}: skipped - could not trace flattened subsystem output for ${portName}\n`
            }
          } else {
            // Regular blocks (including multi-output: atmosphere, etc.)
            const member =
              sourceInfo.signalMemberName ||
              getSignalMemberName(
                sourceInfo.blockName,
                sourceInfo.blockType,
                sourceInfo.portIndex,
                sourceInfo.sourceBlock
              )
            code += `        case ${index}: return ${modelName}_instance.signals.${member};\n`
          }
        } else {
          // Fallback: try outputs struct (may not exist)
          const sanitizedPort = CCodeBuilder.sanitizeIdentifier(portName)
          code += `        case ${index}: return ${modelName}_instance.outputs.${sanitizedPort};\n`
        }
      })
    } else {
      code += `        // No scalar output ports defined\n`
    }

    code += `        default: return 0.0; // Invalid index\n`
    code += `    }\n`
    code += `}\n\n`

    return code
  }

  /**
   * Generate wasm_step function
   */
  private generateWasmStepFunction(modelName: string): string {
    const keepalive = this.wasmOptions.includeEmscriptenExports
      ? 'EMSCRIPTEN_KEEPALIVE\n'
      : ''

    return `// Execute one simulation step
${keepalive}void wasm_step(double dt) {
    // Update dt if changed
    ${modelName}_instance.dt = dt;
    ${modelName}_step(&${modelName}_instance);
}

`
  }

  /**
   * Generate wasm_get_time function
   */
  private generateWasmGetTimeFunction(modelName: string): string {
    const keepalive = this.wasmOptions.includeEmscriptenExports
      ? 'EMSCRIPTEN_KEEPALIVE\n'
      : ''

    return `// Get current simulation time
${keepalive}double wasm_get_time() {
    return ${modelName}_instance.time;
}

`
  }

  /**
   * Generate data collector name array
   * Only includes signal_logger and signal_display blocks
   */
  private generateDataCollectorNameArray(outputMap: Map<string, number>): string {
    // Filter to only logger and display blocks
    const collectors = Array.from(outputMap.entries())
      .filter(([name]) => name.startsWith('logger_') || name.startsWith('display_'))
      .sort((a, b) => a[1] - b[1])

    if (collectors.length === 0) {
      return ''
    }

    let code = '// Data collector name mappings\n'
    code += `static const char* collector_names[] = {\n`
    collectors.forEach(([name], idx) => {
      code += `    "${name}"${idx < collectors.length - 1 ? ',' : ''}\n`
    })
    code += `};\n\n`

    return code
  }

  /**
   * Generate output port name array
   * Only includes actual output ports (excludes logger_ and display_ entries)
   */
  private generateOutputPortNameArray(outputMap: Map<string, number>): string {
    // Filter to only actual output ports (exclude logger and display)
    const outputPorts = Array.from(outputMap.entries())
      .filter(([name]) => !name.startsWith('logger_') && !name.startsWith('display_'))
      .sort((a, b) => a[1] - b[1])

    if (outputPorts.length === 0) {
      return ''
    }

    let code = '// Output port name mappings\n'
    code += `static const char* output_port_names[] = {\n`
    outputPorts.forEach(([name], idx) => {
      code += `    "${name}"${idx < outputPorts.length - 1 ? ',' : ''}\n`
    })
    code += `};\n\n`

    return code
  }

  /**
   * Generate output port info functions for enumerating and accessing output port values
   * Always generates these functions (with stubs if no output ports)
   */
  private generateOutputPortInfoFunctions(
    modelName: string,
    outputMap: Map<string, number>
  ): string {
    const keepalive = this.wasmOptions.includeEmscriptenExports
      ? 'EMSCRIPTEN_KEEPALIVE\n'
      : ''

    // Filter to only actual output ports (exclude logger and display)
    const outputPorts = Array.from(outputMap.entries())
      .filter(([name]) => !name.startsWith('logger_') && !name.startsWith('display_'))
      .sort((a, b) => a[1] - b[1])

    let code = '// Output port info functions\n\n'

    // Get output port count
    code += `// Get number of output ports
${keepalive}int wasm_get_output_port_count() {
    return ${outputPorts.length};
}

`

    // Get output port name
    if (outputPorts.length === 0) {
      code += `// Get output port name by index
${keepalive}const char* wasm_get_output_port_name(int index) {
    (void)index; // Unused - no output ports
    return NULL;
}

`
    } else {
      code += `// Get output port name by index
${keepalive}const char* wasm_get_output_port_name(int index) {
    if (index < 0 || index >= ${outputPorts.length}) return NULL;
    return output_port_names[index];
}

`
    }

    return code
  }

  /**
   * Generate data collection functions for sample retrieval
   * Always generates these functions (with stubs if no collectors) since WASM exports them unconditionally
   */
  private generateDataCollectionFunctions(
    modelName: string,
    outputMap: Map<string, number>,
    collectorTypeMap: Map<string, string>
  ): string {
    const keepalive = this.wasmOptions.includeEmscriptenExports
      ? 'EMSCRIPTEN_KEEPALIVE\n'
      : ''

    // Filter to only logger and display blocks
    const collectors = Array.from(outputMap.entries())
      .filter(([name]) => name.startsWith('logger_') || name.startsWith('display_'))
      .sort((a, b) => a[1] - b[1])

    let code = '// Data collection functions\n\n'

    // Get collector count - always generate, returns 0 if no collectors
    code += `// Get number of data collectors (loggers and displays)
${keepalive}int wasm_get_collector_count() {
    return ${collectors.length};
}

`

    // Get collector name - always generate, returns NULL if no collectors
    if (collectors.length === 0) {
      code += `// Get data collector name by index
${keepalive}const char* wasm_get_collector_name(int index) {
    (void)index; // Unused - no collectors
    return NULL;
}

`
    } else {
      code += `// Get data collector name by index
${keepalive}const char* wasm_get_collector_name(int index) {
    if (index < 0 || index >= ${collectors.length}) return NULL;
    return collector_names[index];
}

`
    }

    // Generate remaining functions - with stubs when no collectors
    if (collectors.length === 0) {
      // Generate stub functions that just return default values
      code += `// Get sample count for a collector (actual number of samples collected, capped at max)
${keepalive}int wasm_get_sample_count(int collector_index) {
    (void)collector_index; // Unused - no collectors
    return 0;
}

`

      code += `// Get current write index for a collector (for circular buffer extraction)
${keepalive}int wasm_get_sample_write_index(int collector_index) {
    (void)collector_index; // Unused - no collectors
    return 0;
}

`

      code += `// Get maximum sample capacity for a collector
${keepalive}int wasm_get_max_samples(int collector_index) {
    (void)collector_index; // Unused - no collectors
    return 0;
}

`

      code += `// Get simulation time of the last recorded sample for a collector
${keepalive}double wasm_get_last_sample_time(int collector_index) {
    (void)collector_index; // Unused - no collectors
    return -1.0;
}

`

      code += `// Get samples array pointer for a collector
// Returns pointer to flat array of doubles (cast from any array type)
${keepalive}double* wasm_get_samples(int collector_index) {
    (void)collector_index; // Unused - no collectors
    return NULL;
}

`

      code += `// Get element size per sample for a collector
// Returns 1 for scalars, array size for vectors, rows*cols for matrices
${keepalive}int wasm_get_element_size(int collector_index) {
    (void)collector_index; // Unused - no collectors
    return 1;
}

`
    } else {
      // Generate real functions with switch statements

      // Get sample count (number of valid samples in circular buffer)
      code += `// Get sample count for a collector (actual number of samples collected, capped at max)
${keepalive}int wasm_get_sample_count(int collector_index) {
    switch(collector_index) {\n`

      collectors.forEach(([name], idx) => {
        // Remove prefix to get sanitized block name
        const blockName = name.replace(/^(logger_|display_)/, '')
        code += `        case ${idx}: return ${modelName}_instance.${blockName}_num_samples;\n`
      })

      code += `        default: return 0;
    }
}

`

      // Get sample write index (current write position in circular buffer)
      code += `// Get current write index for a collector (for circular buffer extraction)
${keepalive}int wasm_get_sample_write_index(int collector_index) {
    switch(collector_index) {\n`

      collectors.forEach(([name], idx) => {
        const blockName = name.replace(/^(logger_|display_)/, '')
        code += `        case ${idx}: return ${modelName}_instance.${blockName}_sample_index;\n`
      })

      code += `        default: return 0;
    }
}

`

      // Get max samples (buffer capacity)
      code += `// Get maximum sample capacity for a collector
${keepalive}int wasm_get_max_samples(int collector_index) {
    switch(collector_index) {\n`

      collectors.forEach(([name], idx) => {
        const blockName = name.replace(/^(logger_|display_)/, '')
        code += `        case ${idx}: return ${modelName}_instance.${blockName}_max_samples;\n`
      })

      code += `        default: return 0;
    }
}

`

      // Get last sample time
      code += `// Get simulation time of the last recorded sample for a collector
${keepalive}double wasm_get_last_sample_time(int collector_index) {
    switch(collector_index) {\n`

      collectors.forEach(([name], idx) => {
        const blockName = name.replace(/^(logger_|display_)/, '')
        code += `        case ${idx}: return ${modelName}_instance.${blockName}_last_sample_time;\n`
      })

      code += `        default: return -1.0;
    }
}

`

      // Get samples pointer
      code += `// Get samples array pointer for a collector
// Returns pointer to flat array of doubles (cast from any array type)
${keepalive}double* wasm_get_samples(int collector_index) {
    switch(collector_index) {\n`

      collectors.forEach(([name], idx) => {
        // Remove prefix to get sanitized block name
        const blockName = name.replace(/^(logger_|display_)/, '')
        // Cast to double* to handle both scalar (double*) and vector/matrix (double (*)[N])
        code += `        case ${idx}: return (double*)${modelName}_instance.${blockName}_samples;\n`
      })

      code += `        default: return NULL;
    }
}

`

      // Get element size (for vector/matrix signals)
      code += `// Get element size per sample for a collector
// Returns 1 for scalars, array size for vectors, rows*cols for matrices
${keepalive}int wasm_get_element_size(int collector_index) {
    switch(collector_index) {\n`

      console.log(`[WasmCodeGenerator] collectorTypeMap entries:`, Array.from(collectorTypeMap.entries()))

      collectors.forEach(([name], idx) => {
        const signalType = collectorTypeMap.get(name) || 'double'
        const elementSize = this.calculateElementSize(signalType)
        console.log(`[WasmCodeGenerator] Collector ${name}: signalType=${signalType}, elementSize=${elementSize}`)
        code += `        case ${idx}: return ${elementSize};\n`
      })

      code += `        default: return 1;
    }
}

`
    }

    return code
  }

  /**
   * Calculate the element size from a type string
   * Examples:
   * - "double" -> 1 (scalar)
   * - "double[3]" -> 3 (vector)
   * - "double[2][3]" -> 6 (matrix)
   */
  private calculateElementSize(typeString: string): number {
    // Match patterns like [3], [2][3], etc.
    const arrayMatch = typeString.match(/\[(\d+)\](?:\[(\d+)\])?/)

    if (!arrayMatch) {
      return 1 // Scalar
    }

    const dim1 = parseInt(arrayMatch[1])
    const dim2 = arrayMatch[2] ? parseInt(arrayMatch[2]) : undefined

    if (dim2 !== undefined) {
      return dim1 * dim2 // Matrix
    }

    return dim1 // Vector
  }

  /**
   * Generate wasm_cleanup function
   *
   * @param modelName - The sanitized model name
   * @param hasCleanupFunction - Whether the C source has a cleanup function defined
   */
  private generateWasmCleanupFunction(modelName: string, hasCleanupFunction: boolean): string {
    const keepalive = this.wasmOptions.includeEmscriptenExports
      ? 'EMSCRIPTEN_KEEPALIVE\n'
      : ''

    if (!hasCleanupFunction) {
      // No cleanup function exists in C source - generate empty wrapper
      return `// Cleanup allocated memory (no cleanup function in model)
${keepalive}void wasm_cleanup() {
    // Nothing to clean up
}

`
    }

    return `// Cleanup allocated memory
${keepalive}void wasm_cleanup() {
    ${modelName}_cleanup(&${modelName}_instance);
}

`
  }

  /**
   * Generate debug functions (optional)
   */
  private generateWasmDebugFunctions(
    modelName: string,
    inputMap: Map<string, number>,
    outputMap: Map<string, number>
  ): string {
    const keepalive = this.wasmOptions.includeEmscriptenExports
      ? 'EMSCRIPTEN_KEEPALIVE\n'
      : ''

    let code = '// Debug functions\n\n'

    // Get input count
    code += `${keepalive}int wasm_get_input_count() {
    return ${inputMap.size};
}

`

    // Get output count
    code += `${keepalive}int wasm_get_output_count() {
    return ${outputMap.size};
}

`

    // Get input name
    code += `${keepalive}const char* wasm_get_input_name(int index) {
    if (index < 0 || index >= ${inputMap.size}) return NULL;
    return input_names[index];
}

`

    // Get output name
    code += `${keepalive}const char* wasm_get_output_name(int index) {
    if (index < 0 || index >= ${outputMap.size}) return NULL;
    return output_names[index];
}

`

    return code
  }
}
