/**
 * WASM Code Generator
 *
 * Extends the base CodeGenerator to add WebAssembly-specific features:
 * - EMSCRIPTEN_KEEPALIVE macros for exported functions
 * - Simplified interface functions for JS interop
 * - Input/output index mapping
 * - Memory management helpers
 */

import { CodeGenerator, CodeGenerationOptions, CodeGenerationResult } from '@/lib/codegen/CodeGenerator'
import { Sheet } from '@/lib/simulationEngine'
import { CCodeBuilder } from '@/lib/codegen/CCodeBuilder'

export interface WasmCodeGenerationOptions extends CodeGenerationOptions {
  /** Whether to include Emscripten-specific exports (default: true) */
  includeEmscriptenExports?: boolean

  /** Whether to include debug/logging functions (default: false) */
  includeDebugFunctions?: boolean
}

export interface WasmCodeGenerationResult extends CodeGenerationResult {
  /** Model name (for reference) */
  modelName: string

  /** Generated WASM wrapper file content */
  wasmWrapper: string

  /** Input port index mapping */
  inputMap: Map<string, number>

  /** Output port index mapping */
  outputMap: Map<string, number>
}

/**
 * Code generator that produces WASM-compatible C code
 */
export class WasmCodeGenerator extends CodeGenerator {
  private wasmOptions: Required<WasmCodeGenerationOptions>

  constructor(options: WasmCodeGenerationOptions = {}) {
    super(options)
    this.wasmOptions = {
      ...this.options,
      includeEmscriptenExports: options.includeEmscriptenExports ?? true,
      includeDebugFunctions: options.includeDebugFunctions ?? false
    }
  }

  /**
   * Generate C code with WASM exports
   */
  generateWasm(sheets: Sheet[]): WasmCodeGenerationResult {
    // Generate base code using parent class
    const baseResult = this.generate(sheets)

    // Flatten the model to run type propagation (same as base code generation does)
    const { ModelFlattener } = require('../../codegen/ModelFlattener')
    const { TypePropagator } = require('../../codegen/TypePropagator')

    const flattener = new ModelFlattener({
      preserveOriginalNames: true,
      generateEnableTracking: true,
      namePrefix: '',
      nameSeparator: '_'
    })

    const flatteningResult = flattener.flattenModel(sheets, this.options.modelName)
    const typePropagator = new TypePropagator(flatteningResult.model)
    const typeMap = typePropagator.propagate()

    console.log(`[WasmCodeGenerator] typeMap entries:`, Array.from(typeMap.entries()))
    console.log(`[WasmCodeGenerator] flattenedModel.blocks:`, flatteningResult.model.blocks.map((b: any) => ({ originalId: b.originalId, name: b.block.name, type: b.block.type })))

    // Extract input/output mappings with type information
    const { inputMap, outputMap, outputSourceMap, collectorTypeMap, outputTypeMap } = this.extractPortMappings(sheets, typeMap, flatteningResult.model)

    // Check if cleanup function was actually generated by examining the header
    // This is the authoritative source - if the header doesn't declare it, it doesn't exist
    const sanitizedName = CCodeBuilder.sanitizeIdentifier(this.options.modelName)
    const hasCleanupFunction = baseResult.header.includes(`${sanitizedName}_cleanup`)

    console.log(`[WasmCodeGenerator] Model: ${sanitizedName}, hasCleanupFunction: ${hasCleanupFunction}`)
    if (hasCleanupFunction) {
      console.log('[WasmCodeGenerator] Cleanup function found in header')
    } else {
      console.log('[WasmCodeGenerator] No cleanup function in header - will generate empty wrapper')
    }

    // Generate WASM wrapper
    const wasmWrapper = this.generateWasmWrapper(
      this.options.modelName,
      inputMap,
      outputMap,
      outputSourceMap,
      collectorTypeMap,
      outputTypeMap,
      hasCleanupFunction
    )

    return {
      ...baseResult,
      modelName: this.options.modelName,
      wasmWrapper,
      inputMap,
      outputMap
    }
  }

  /**
   * Extract input and output port mappings for index-based access
   *
   * Includes:
   * - input_port blocks as inputs
   * - output_port blocks as outputs
   * - signal_logger blocks as outputs (for scope data retrieval)
   * - signal_display blocks as outputs (for visualization data retrieval)
   */
  private extractPortMappings(
    sheets: Sheet[],
    typeMap: Map<string, string>,
    flattenedModel: any
  ): {
    inputMap: Map<string, number>
    outputMap: Map<string, number>
    outputSourceMap: Map<string, string> // Maps output port name to source block name
    collectorTypeMap: Map<string, string> // Maps collector name to input signal type
    outputTypeMap: Map<string, string> // Maps output port name to signal type
  } {
    const inputMap = new Map<string, number>()
    const outputMap = new Map<string, number>()
    const outputSourceMap = new Map<string, string>()
    const collectorTypeMap = new Map<string, string>()
    const outputTypeMap = new Map<string, string>()

    let inputIndex = 0
    let outputIndex = 0

    // Helper function to get type from typeMap
    const getBlockType = (blockId: string, fallbackType: string = 'double'): string => {
      // Find the flattened block by original ID
      const flattenedBlock = flattenedModel.blocks.find((fb: any) => fb.originalId === blockId)
      if (flattenedBlock) {
        const mappedType = typeMap.get(flattenedBlock.originalId)
        console.log(`[getBlockType] blockId=${blockId}, flattenedBlock.originalId=${flattenedBlock.originalId}, mappedType=${mappedType}`)
        if (mappedType) {
          return mappedType
        }
      } else {
        console.log(`[getBlockType] blockId=${blockId}, flattenedBlock not found`)
      }
      return fallbackType
    }

    // Process all sheets to find input/output ports and signal loggers
    for (const sheet of sheets) {
      for (const block of sheet.blocks) {
        if (block.type === 'input_port') {
          const portName = block.parameters?.portName || block.name
          inputMap.set(portName, inputIndex++)
        } else if (block.type === 'output_port') {
          const portName = block.parameters?.portName || block.name
          outputMap.set(portName, outputIndex++)

          // Find the connection that feeds this output port
          const feedingConnection = sheet.connections.find(conn => conn.targetBlockId === block.id)
          if (feedingConnection) {
            const sourceBlock = sheet.blocks.find(b => b.id === feedingConnection.sourceBlockId)
            if (sourceBlock) {
              outputSourceMap.set(portName, sourceBlock.name)
              // Get the type from typeMap (handles Transfer Functions properly)
              const sourceType = getBlockType(sourceBlock.id, sourceBlock.parameters?.dataType || 'double')
              outputTypeMap.set(portName, sourceType)
            }
          }
        } else if (block.type === 'signal_logger') {
          // Treat signal loggers as outputs for scope data access
          // Use sanitized block name to avoid issues with spaces
          const loggerName = `logger_${CCodeBuilder.sanitizeIdentifier(block.name)}`
          outputMap.set(loggerName, outputIndex++)

          // Find the connection that feeds this signal logger
          const feedingConnection = sheet.connections.find(conn => conn.targetBlockId === block.id)
          if (feedingConnection) {
            const sourceBlock = sheet.blocks.find(b => b.id === feedingConnection.sourceBlockId)
            if (sourceBlock) {
              outputSourceMap.set(loggerName, sourceBlock.name)
              // Get the type from typeMap (handles Transfer Functions properly)
              const sourceType = getBlockType(sourceBlock.id, sourceBlock.parameters?.dataType || 'double')
              collectorTypeMap.set(loggerName, sourceType)
            }
          }
        } else if (block.type === 'signal_display') {
          // Treat signal displays as outputs for visualization data access
          // Use sanitized block name to avoid issues with spaces
          const displayName = `display_${CCodeBuilder.sanitizeIdentifier(block.name)}`
          outputMap.set(displayName, outputIndex++)

          // Find the connection that feeds this signal display
          const feedingConnection = sheet.connections.find(conn => conn.targetBlockId === block.id)
          if (feedingConnection) {
            const sourceBlock = sheet.blocks.find(b => b.id === feedingConnection.sourceBlockId)
            if (sourceBlock) {
              outputSourceMap.set(displayName, sourceBlock.name)
              // Get the type from typeMap (handles Transfer Functions properly)
              const sourceType = getBlockType(sourceBlock.id, sourceBlock.parameters?.dataType || 'double')
              collectorTypeMap.set(displayName, sourceType)
            }
          }
        }
      }
    }

    return { inputMap, outputMap, outputSourceMap, collectorTypeMap, outputTypeMap }
  }

  /**
   * Generate WASM wrapper file with Emscripten exports
   */
  private generateWasmWrapper(
    modelName: string,
    inputMap: Map<string, number>,
    outputMap: Map<string, number>,
    outputSourceMap: Map<string, string>,
    collectorTypeMap: Map<string, string>,
    outputTypeMap: Map<string, string>,
    hasCleanupFunction: boolean
  ): string {
    const sanitizedName = CCodeBuilder.sanitizeIdentifier(modelName)
    let wrapper = ''

    // Header comments
    const exportNote = this.wasmOptions.includeEmscriptenExports
      ? '\n * Functions are exported using EMSCRIPTEN_KEEPALIVE for direct calling from JS.'
      : ''
    wrapper += `/*
 * WASM Wrapper for ${modelName}
 *
 * This file provides a simple interface for WebAssembly/JavaScript interop.${exportNote}
 */

`

    // Includes
    wrapper += `#include "${sanitizedName}.h"\n\n`

    if (this.wasmOptions.includeEmscriptenExports) {
      wrapper += `#ifdef __EMSCRIPTEN__
#include <emscripten.h>
#else
#define EMSCRIPTEN_KEEPALIVE
#endif

`
    }

    // Global model instance
    wrapper += `// Global model instance
static ${sanitizedName}_t ${sanitizedName}_instance = {0};

`

    // Input/output name arrays (for debugging)
    if (this.wasmOptions.includeDebugFunctions) {
      wrapper += this.generatePortNameArrays(inputMap, outputMap)
    }

    // Data collector name array (for sample retrieval)
    wrapper += this.generateDataCollectorNameArray(outputMap)

    // Initialize function
    wrapper += this.generateWasmInitFunction(sanitizedName)

    // Set input function
    wrapper += this.generateWasmSetInputFunction(sanitizedName, inputMap)

    // Get output function
    wrapper += this.generateWasmGetOutputFunction(sanitizedName, outputMap, outputSourceMap, outputTypeMap)

    // Step function
    wrapper += this.generateWasmStepFunction(sanitizedName)

    // Get time function
    wrapper += this.generateWasmGetTimeFunction(sanitizedName)

    // Data collection functions (for logger/display sample retrieval)
    wrapper += this.generateDataCollectionFunctions(sanitizedName, outputMap, collectorTypeMap)

    // Cleanup function (always generate, but conditionally call C cleanup based on what was actually generated)
    wrapper += this.generateWasmCleanupFunction(sanitizedName, hasCleanupFunction)

    // Debug functions (optional)
    if (this.wasmOptions.includeDebugFunctions) {
      wrapper += this.generateWasmDebugFunctions(sanitizedName, inputMap, outputMap)
    }

    return wrapper
  }

  /**
   * Generate port name arrays for debugging
   */
  private generatePortNameArrays(
    inputMap: Map<string, number>,
    outputMap: Map<string, number>
  ): string {
    let code = '// Port name mappings for debugging\n'

    // Input names
    code += `static const char* input_names[] = {\n`
    const sortedInputs = Array.from(inputMap.entries())
      .sort((a, b) => a[1] - b[1])
    sortedInputs.forEach(([name], idx) => {
      code += `    "${name}"${idx < sortedInputs.length - 1 ? ',' : ''}\n`
    })
    code += `};\n\n`

    // Output names
    code += `static const char* output_names[] = {\n`
    const sortedOutputs = Array.from(outputMap.entries())
      .sort((a, b) => a[1] - b[1])
    sortedOutputs.forEach(([name], idx) => {
      code += `    "${name}"${idx < sortedOutputs.length - 1 ? ',' : ''}\n`
    })
    code += `};\n\n`

    return code
  }

  /**
   * Generate wasm_init function
   */
  private generateWasmInitFunction(modelName: string): string {
    const keepalive = this.wasmOptions.includeEmscriptenExports
      ? 'EMSCRIPTEN_KEEPALIVE\n'
      : ''

    return `// Initialize the model with a given timestep
${keepalive}void wasm_init(double dt) {
    ${modelName}_init(&${modelName}_instance, dt);
}

`
  }

  /**
   * Generate wasm_set_input function
   */
  private generateWasmSetInputFunction(
    modelName: string,
    inputMap: Map<string, number>
  ): string {
    const keepalive = this.wasmOptions.includeEmscriptenExports
      ? 'EMSCRIPTEN_KEEPALIVE\n'
      : ''

    let code = `// Set an input value by index
${keepalive}void wasm_set_input(int index, double value) {
    switch(index) {\n`

    // Generate switch cases for each input
    const sortedInputs = Array.from(inputMap.entries())
      .sort((a, b) => a[1] - b[1])

    sortedInputs.forEach(([portName, index]) => {
      const sanitizedPort = CCodeBuilder.sanitizeIdentifier(portName)
      code += `        case ${index}: ${modelName}_instance.inputs.${sanitizedPort} = value; break;\n`
    })

    code += `        default: break; // Invalid index\n`
    code += `    }\n`
    code += `}\n\n`

    return code
  }

  /**
   * Generate wasm_get_output function
   */
  private generateWasmGetOutputFunction(
    modelName: string,
    outputMap: Map<string, number>,
    outputSourceMap: Map<string, string>,
    outputTypeMap: Map<string, string>
  ): string {
    const keepalive = this.wasmOptions.includeEmscriptenExports
      ? 'EMSCRIPTEN_KEEPALIVE\n'
      : ''

    let code = `// Get an output value by index
// Note: Only supports scalar outputs. For vector/matrix data, use Signal Display blocks.
${keepalive}double wasm_get_output(int index) {
    switch(index) {\n`

    // Generate switch cases for each output
    console.log(`[WasmCodeGenerator] outputMap entries:`, Array.from(outputMap.entries()))
    console.log(`[WasmCodeGenerator] outputTypeMap entries:`, Array.from(outputTypeMap.entries()))

    const sortedOutputs = Array.from(outputMap.entries())
      .sort((a, b) => a[1] - b[1])
      // Filter out logger and display blocks - they're not real output ports
      .filter(([name]) => !name.startsWith('logger_') && !name.startsWith('display_'))
      // Filter out vector/matrix outputs - only support scalars
      .filter(([name]) => {
        const outputType = outputTypeMap.get(name) || 'double'
        console.log(`[WasmCodeGenerator] Checking output ${name}: type=${outputType}, isScalar=${!outputType.includes('[')}`)
        // Check if it's a scalar (no array brackets)
        return !outputType.includes('[')
      })

    console.log(`[WasmCodeGenerator] Filtered outputs for wasm_get_output:`, sortedOutputs)

    if (sortedOutputs.length > 0) {
      sortedOutputs.forEach(([portName, index]) => {
        // Output ports are fed by signals, not stored directly in outputs struct
        // Use the source signal if available
        const sourceBlock = outputSourceMap.get(portName)
        if (sourceBlock) {
          const sanitizedSource = CCodeBuilder.sanitizeIdentifier(sourceBlock)
          code += `        case ${index}: return ${modelName}_instance.signals.${sanitizedSource};\n`
        } else {
          // Fallback: try outputs struct (may not exist)
          const sanitizedPort = CCodeBuilder.sanitizeIdentifier(portName)
          code += `        case ${index}: return ${modelName}_instance.outputs.${sanitizedPort};\n`
        }
      })
    } else {
      code += `        // No scalar output ports defined\n`
    }

    code += `        default: return 0.0; // Invalid index\n`
    code += `    }\n`
    code += `}\n\n`

    return code
  }

  /**
   * Generate wasm_step function
   */
  private generateWasmStepFunction(modelName: string): string {
    const keepalive = this.wasmOptions.includeEmscriptenExports
      ? 'EMSCRIPTEN_KEEPALIVE\n'
      : ''

    return `// Execute one simulation step
${keepalive}void wasm_step(double dt) {
    // Update dt if changed
    ${modelName}_instance.dt = dt;
    ${modelName}_step(&${modelName}_instance);
}

`
  }

  /**
   * Generate wasm_get_time function
   */
  private generateWasmGetTimeFunction(modelName: string): string {
    const keepalive = this.wasmOptions.includeEmscriptenExports
      ? 'EMSCRIPTEN_KEEPALIVE\n'
      : ''

    return `// Get current simulation time
${keepalive}double wasm_get_time() {
    return ${modelName}_instance.time;
}

`
  }

  /**
   * Generate data collector name array
   * Only includes signal_logger and signal_display blocks
   */
  private generateDataCollectorNameArray(outputMap: Map<string, number>): string {
    // Filter to only logger and display blocks
    const collectors = Array.from(outputMap.entries())
      .filter(([name]) => name.startsWith('logger_') || name.startsWith('display_'))
      .sort((a, b) => a[1] - b[1])

    if (collectors.length === 0) {
      return ''
    }

    let code = '// Data collector name mappings\n'
    code += `static const char* collector_names[] = {\n`
    collectors.forEach(([name], idx) => {
      code += `    "${name}"${idx < collectors.length - 1 ? ',' : ''}\n`
    })
    code += `};\n\n`

    return code
  }

  /**
   * Generate data collection functions for sample retrieval
   */
  private generateDataCollectionFunctions(
    modelName: string,
    outputMap: Map<string, number>,
    collectorTypeMap: Map<string, string>
  ): string {
    const keepalive = this.wasmOptions.includeEmscriptenExports
      ? 'EMSCRIPTEN_KEEPALIVE\n'
      : ''

    // Filter to only logger and display blocks
    const collectors = Array.from(outputMap.entries())
      .filter(([name]) => name.startsWith('logger_') || name.startsWith('display_'))
      .sort((a, b) => a[1] - b[1])

    if (collectors.length === 0) {
      return ''
    }

    let code = '// Data collection functions\n\n'

    // Get collector count
    code += `// Get number of data collectors (loggers and displays)
${keepalive}int wasm_get_collector_count() {
    return ${collectors.length};
}

`

    // Get collector name
    code += `// Get data collector name by index
${keepalive}const char* wasm_get_collector_name(int index) {
    if (index < 0 || index >= ${collectors.length}) return NULL;
    return collector_names[index];
}

`

    // Get sample count
    code += `// Get sample count for a collector
${keepalive}int wasm_get_sample_count(int collector_index) {
    switch(collector_index) {\n`

    collectors.forEach(([name], idx) => {
      // Remove prefix to get sanitized block name
      const blockName = name.replace(/^(logger_|display_)/, '')
      code += `        case ${idx}: return ${modelName}_instance.${blockName}_sample_index;\n`
    })

    code += `        default: return 0;
    }
}

`

    // Get samples pointer
    code += `// Get samples array pointer for a collector
// Returns pointer to flat array of doubles (cast from any array type)
${keepalive}double* wasm_get_samples(int collector_index) {
    switch(collector_index) {\n`

    collectors.forEach(([name], idx) => {
      // Remove prefix to get sanitized block name
      const blockName = name.replace(/^(logger_|display_)/, '')
      // Cast to double* to handle both scalar (double*) and vector/matrix (double (*)[N])
      code += `        case ${idx}: return (double*)${modelName}_instance.${blockName}_samples;\n`
    })

    code += `        default: return NULL;
    }
}

`

    // Get element size (for vector/matrix signals)
    code += `// Get element size per sample for a collector
// Returns 1 for scalars, array size for vectors, rows*cols for matrices
${keepalive}int wasm_get_element_size(int collector_index) {
    switch(collector_index) {\n`

    collectors.forEach(([name], idx) => {
      const signalType = collectorTypeMap.get(name) || 'double'
      const elementSize = this.calculateElementSize(signalType)
      code += `        case ${idx}: return ${elementSize};\n`
    })

    code += `        default: return 1;
    }
}

`

    return code
  }

  /**
   * Calculate the element size from a type string
   * Examples:
   * - "double" -> 1 (scalar)
   * - "double[3]" -> 3 (vector)
   * - "double[2][3]" -> 6 (matrix)
   */
  private calculateElementSize(typeString: string): number {
    // Match patterns like [3], [2][3], etc.
    const arrayMatch = typeString.match(/\[(\d+)\](?:\[(\d+)\])?/)

    if (!arrayMatch) {
      return 1 // Scalar
    }

    const dim1 = parseInt(arrayMatch[1])
    const dim2 = arrayMatch[2] ? parseInt(arrayMatch[2]) : undefined

    if (dim2 !== undefined) {
      return dim1 * dim2 // Matrix
    }

    return dim1 // Vector
  }

  /**
   * Generate wasm_cleanup function
   *
   * @param modelName - The sanitized model name
   * @param hasCleanupFunction - Whether the C source has a cleanup function defined
   */
  private generateWasmCleanupFunction(modelName: string, hasCleanupFunction: boolean): string {
    const keepalive = this.wasmOptions.includeEmscriptenExports
      ? 'EMSCRIPTEN_KEEPALIVE\n'
      : ''

    if (!hasCleanupFunction) {
      // No cleanup function exists in C source - generate empty wrapper
      return `// Cleanup allocated memory (no cleanup function in model)
${keepalive}void wasm_cleanup() {
    // Nothing to clean up
}

`
    }

    return `// Cleanup allocated memory
${keepalive}void wasm_cleanup() {
    ${modelName}_cleanup(&${modelName}_instance);
}

`
  }

  /**
   * Generate debug functions (optional)
   */
  private generateWasmDebugFunctions(
    modelName: string,
    inputMap: Map<string, number>,
    outputMap: Map<string, number>
  ): string {
    const keepalive = this.wasmOptions.includeEmscriptenExports
      ? 'EMSCRIPTEN_KEEPALIVE\n'
      : ''

    let code = '// Debug functions\n\n'

    // Get input count
    code += `${keepalive}int wasm_get_input_count() {
    return ${inputMap.size};
}

`

    // Get output count
    code += `${keepalive}int wasm_get_output_count() {
    return ${outputMap.size};
}

`

    // Get input name
    code += `${keepalive}const char* wasm_get_input_name(int index) {
    if (index < 0 || index >= ${inputMap.size}) return NULL;
    return input_names[index];
}

`

    // Get output name
    code += `${keepalive}const char* wasm_get_output_name(int index) {
    if (index < 0 || index >= ${outputMap.size}) return NULL;
    return output_names[index];
}

`

    return code
  }
}
